export const FREE_TIER_MAX_CONVERSATIONS = 1;
export const FREE_TIER_MAX_TOKENS = 20_000;

export const DEFAULT_INCLUDED_TOKEN_CREDIT_USD = 10;
export const PAID_TIER_ESTIMATED_COST_PER_1K_TOKENS_USD = 0.02;

export const MIN_OVERAGE_INVOICE_THRESHOLD_USD = 0.5;
