/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreeIdRouteImport } from './routes/tree.$id'
import { Route as LogsIdRouteImport } from './routes/logs.$id'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe-webhook'
import { Route as ApiCreateCheckoutRouteImport } from './routes/api.create-checkout'
import { Route as ApiChatRouteImport } from './routes/api.chat'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreeIdRoute = TreeIdRouteImport.update({
  id: '/tree/$id',
  path: '/tree/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIdRoute = LogsIdRouteImport.update({
  id: '/logs/$id',
  path: '/logs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateCheckoutRoute = ApiCreateCheckoutRouteImport.update({
  id: '/api/create-checkout',
  path: '/api/create-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/sign-in': typeof SignInRoute
  '/api/chat': typeof ApiChatRoute
  '/api/create-checkout': typeof ApiCreateCheckoutRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/chat/$id': typeof ChatIdRoute
  '/logs/$id': typeof LogsIdRoute
  '/tree/$id': typeof TreeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/sign-in': typeof SignInRoute
  '/api/chat': typeof ApiChatRoute
  '/api/create-checkout': typeof ApiCreateCheckoutRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/chat/$id': typeof ChatIdRoute
  '/logs/$id': typeof LogsIdRoute
  '/tree/$id': typeof TreeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/sign-in': typeof SignInRoute
  '/api/chat': typeof ApiChatRoute
  '/api/create-checkout': typeof ApiCreateCheckoutRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/chat/$id': typeof ChatIdRoute
  '/logs/$id': typeof LogsIdRoute
  '/tree/$id': typeof TreeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pricing'
    | '/sign-in'
    | '/api/chat'
    | '/api/create-checkout'
    | '/api/stripe-webhook'
    | '/chat/$id'
    | '/logs/$id'
    | '/tree/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/sign-in'
    | '/api/chat'
    | '/api/create-checkout'
    | '/api/stripe-webhook'
    | '/chat/$id'
    | '/logs/$id'
    | '/tree/$id'
  id:
    | '__root__'
    | '/'
    | '/pricing'
    | '/sign-in'
    | '/api/chat'
    | '/api/create-checkout'
    | '/api/stripe-webhook'
    | '/chat/$id'
    | '/logs/$id'
    | '/tree/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PricingRoute: typeof PricingRoute
  SignInRoute: typeof SignInRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCreateCheckoutRoute: typeof ApiCreateCheckoutRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ChatIdRoute: typeof ChatIdRoute
  LogsIdRoute: typeof LogsIdRoute
  TreeIdRoute: typeof TreeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tree/$id': {
      id: '/tree/$id'
      path: '/tree/$id'
      fullPath: '/tree/$id'
      preLoaderRoute: typeof TreeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/$id': {
      id: '/logs/$id'
      path: '/logs/$id'
      fullPath: '/logs/$id'
      preLoaderRoute: typeof LogsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-checkout': {
      id: '/api/create-checkout'
      path: '/api/create-checkout'
      fullPath: '/api/create-checkout'
      preLoaderRoute: typeof ApiCreateCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PricingRoute: PricingRoute,
  SignInRoute: SignInRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCreateCheckoutRoute: ApiCreateCheckoutRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ChatIdRoute: ChatIdRoute,
  LogsIdRoute: LogsIdRoute,
  TreeIdRoute: TreeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
